# Generated by Django 3.1 on 2020-12-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intl', models.BooleanField(default=False)),
                ('natl', models.BooleanField(default=False)),
                ('i_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('n_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info', to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fever', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('nasal', models.BooleanField(default=False)),
                ('tired', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('cold', models.BooleanField(default=False)),
                ('smell', models.BooleanField(default=False)),
                ('body_ache', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('conjunctivitis', models.BooleanField(default=False)),
                ('rash', models.BooleanField(default=False)),
                ('discolor', models.BooleanField(default=False)),
                ('breathe', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('speech_loss', models.BooleanField(default=False)),
                ('uncon', models.BooleanField(default=False)),
                ('lung', models.BooleanField(default=False)),
                ('heart', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('hypten', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('kidney', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False)),
                ('stroke', models.BooleanField(default=False)),
                ('immunity', models.BooleanField(default=False)),
                ('lived_covid', models.BooleanField(default=False)),
                ('frontline', models.BooleanField(default=False)),
                ('crowded', models.BooleanField(default=False)),
                ('gathering', models.BooleanField(default=False)),
                ('containment', models.BooleanField(default=False)),
                ('medical_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='chatbot.user')),
            ],
        ),
    ]
