# Generated by Django 3.1.3 on 2020-11-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('fever', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('nasal', models.BooleanField(default=False)),
                ('tired', models.BooleanField(default=False)),
                ('smell', models.BooleanField(default=False)),
                ('body_ache', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('conjunctivitis', models.BooleanField(default=False)),
                ('rash', models.BooleanField(default=False)),
                ('discolor', models.BooleanField(default=False)),
                ('breathe', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('speech_loss', models.BooleanField(default=False)),
                ('uncon', models.BooleanField(default=False)),
                ('lung', models.BooleanField(default=False)),
                ('heart', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('hypten', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('kidney', models.BooleanField(default=False)),
                ('stroke', models.BooleanField(default=False)),
                ('immunity', models.BooleanField(default=False)),
                ('lived_covid', models.BooleanField(default=False)),
                ('frontline', models.BooleanField(default=False)),
                ('crowded', models.BooleanField(default=False)),
                ('neighbor', models.BooleanField(default=False)),
                ('public_trans', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='chatbot.user')),
            ],
        ),
    ]
