# Generated by Django 3.1.3 on 2020-11-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
