# Generated by Django 3.1.3 on 2020-11-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20201123_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intl', models.BooleanField(default=False)),
                ('natl', models.BooleanField(default=False)),
                ('i_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('n_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info', to='chatbot.user')),
            ],
        ),
    ]
