# Generated by Django 3.1.3 on 2020-11-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_travelinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='medical_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='travel_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='chatbot.user')),
            ],
        ),
    ]
