# Generated by Django 3.1.3 on 2020-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20201124_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='liver',
            field=models.BooleanField(default=False),
        ),
    ]
