# Generated by Django 3.1.3 on 2020-11-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20201124_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='neighbor',
            new_name='containment',
        ),
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='public_trans',
            new_name='gathering',
        ),
    ]
