# Generated by Django 3.1 on 2020-11-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_user_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='date',
        ),
    ]
